name: Build and Deploy with JitPack

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to JitPack
      env:
        GENTOO_RELEASE_API_KEY: EYOmgqkSmm55kxojN6ck7a4SKlvKltpd9X5r898k # ${{ secrets.GENTOO_RELEASE_API_KEY }}
        GENTOO_RELEASE_BASE_URL: https://byg7k8r4gi.execute-api.ap-northeast-2.amazonaws.com/prod # ${{ secrets.GENTOO_RELEASE_BASE_URL }}
      run: |
        ./gradlew publishReleasePublicationToMavenLocal
